Backport changes to Lighthouse from autospidergen branch
alltheplaces/alltheplaces pull request #10018
Opened 2024-08-31 04:28 UTC by CloCkWeRX

2024-08-31 07:52 UTC, davidhicks requested changes

2024-08-31 07:52 UTC, davidhicks commented on locations/storefinders/lighthouse.py
> +            item["addr_full"] = re.sub(
This should use `locations.pipelines.address_clean_up.clean_address` instead.

2024-08-31 11:33 UTC, davidhicks requested changes

2024-08-31 11:33 UTC, davidhicks commented on locations/storefinders/lighthouse.py
> +            item["addr_full"] = ", ".join(
Correct usage is `item["addr_full"] = clean_address(["Line 1", "Line 2", "Line 3"])`

2024-09-04 01:23 UTC, davidhicks approved these changes

2024-09-04 01:24 UTC, CloCkWeRX commented
@iandees - good to go!

2024-09-04 01:30 UTC, merged