Autodetect storefrontgateway
alltheplaces/alltheplaces pull request #10096
Opened 2024-09-04 07:57 UTC by CloCkWeRX

Part of #10063

2024-09-04 07:57 UTC, CloCkWeRX commented
@davidhicks

2024-09-04 08:25 UTC, CloCkWeRX commented on locations/storefinders/storefrontgateway.py
> +        DetectionResponseRule(js_objects={"start_urls": r"[window.__PRELOADED_STATE__.settings.env.PUBLIC_API]"}),
```suggestion
        DetectionResponseRule(js_objects={"start_urls": r"[window.__PRELOADED_STATE__.settings.env.PUBLIC_API + 'stores']"}),
```

2024-09-04 10:23 UTC, davidhicks requested changes

2024-09-04 10:23 UTC, davidhicks commented on locations/storefinders/storefrontgateway.py
> +        DetectionRequestRule(url=r"^https?:\/\/storefrontgateway\.[w\.-]+/api/stores"),
The last part of the regex doesn't look right from a quick look, for example, the `w` in the regex class is probably meant to be `\w` as a character class and the hyphen in the regex class is incorrect and probably meant to be escaped. Would the following work: `r"^https?:\/\/storefrontgateway(?:\.[\w\-]+)+\/api\/stores\/?$"`   Still not great for domain matching as it'll match invalid DNS names still, but it's not too bad of an approximation.

2024-09-04 10:23 UTC, davidhicks commented on locations/storefinders/storefrontgateway.py
> +    api_key: str = ""
What is `api_key` used for?

2024-09-04 10:24 UTC, davidhicks commented
> @davidhicks

Thanks! Looks good just two minor comments for consideration

2024-09-04 10:29 UTC, davidhicks commented on locations/storefinders/storefrontgateway.py
> +        DetectionRequestRule(url=r"^https?:\/\/storefrontgateway\.[w\.-]+/api/stores"),
Oops just occurred to be the named PCRE capture group is missing. Suggestion is then:

`DetectionRequestRule(url=r"^(?P<start_urls__list>https?:\/\/storefrontgateway(?:\.[\w\-]+)+\/api\/stores)\/?$")`

2024-09-04 11:08 UTC, CloCkWeRX commented on locations/storefinders/storefrontgateway.py
> +        DetectionRequestRule(url=r"^https?:\/\/storefrontgateway\.[w\.-]+/api/stores"),
```suggestion
       DetectionRequestRule(url=r"^(?P<start_urls__list>https?:\/\/storefrontgateway(?:\.[\w\-]+)+\/api\/stores)\/?$")
```

2024-09-04 11:08 UTC, CloCkWeRX commented on locations/storefinders/storefrontgateway.py
> +    api_key: str = ""
```suggestion
```

2024-09-05 08:21 UTC, davidhicks approved these changes

2024-09-05 08:21 UTC, merged