[GreatWallMotorBWNAZA] Fix Spider
alltheplaces/alltheplaces pull request #11557
Opened 2024-12-02 13:15 UTC by mohit-sharma2194

`Fixes : updated start_urls to fix spider`

{'atp/brand/GWM': 68,
 'atp/brand/GWM;Haval': 2,
 'atp/brand/Haval': 26,
 'atp/brand_wikidata/Q1117001': 68,
 'atp/brand_wikidata/Q1117001;Q28223947': 2,
 'atp/brand_wikidata/Q28223947': 26,
 'atp/category/shop/car': 96,
 'atp/field/brand_wikidata/invalid': 2,
 'atp/field/city/missing': 7,
 'atp/field/country/from_website_url': 96,
 'atp/field/email/missing': 96,
 'atp/field/image/missing': 96,
 'atp/field/name/missing': 2,
 'atp/field/opening_hours/missing': 96,
 'atp/field/operator/missing': 96,
 'atp/field/operator_wikidata/missing': 96,
 'atp/field/postcode/missing': 7,
 'atp/field/state/missing': 2,
 'atp/field/street_address/missing': 96,
 'atp/field/twitter/missing': 96,
 'atp/great_wall_motor_bw_na_za/unknown_brand/': 1,
 'atp/item_scraped_host_count/www.gwm.co.za': 96,
 'atp/nsi/brand_missing': 2,
 'atp/nsi/cc_match': 94,
 'downloader/request_bytes': 642,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 16027,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/404': 1,
 'elapsed_time_seconds': 2.593776,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 12, 2, 13, 10, 17, 310588, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 57422,
 'httpcompression/response_count': 2,
 'item_scraped_count': 96,
 'log_count/DEBUG': 110,
 'log_count/INFO': 9,
 'response_received_count': 2,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/404': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 12, 2, 13, 10, 14, 716812, tzinfo=datetime.timezone.utc)}

2024-12-02 22:01 UTC, Cj-Malone requested changes
This url will change next time they update the site.

2024-12-02 22:08 UTC, iandees commented on locations/spiders/great_wall_motor_bw_na_za.py
> -
Please don't delete whitespace.

2024-12-03 05:04 UTC, mohit-sharma2194 commented
> This url will change next time they update the site.

Any suggestions?

2024-12-03 09:27 UTC, Cj-Malone commented
You could parse all the links out of `//script[contains(text(), "Dealer")]` on `https://www.gwm.co.za/dealerships` and only parse the one that contains `category:"Dealership"`. But I don't think it's worth the effort TBH.

2025-05-15 10:02 UTC, mohit-sharma2194 commented
Closing the PR as website revisit requires to find other solution.

2025-05-15 10:02 UTC, closed without merging