McGrath: Rewrite to use new API
alltheplaces/alltheplaces pull request #11588
Opened 2024-12-04 22:08 UTC by impiaaa

2024-12-05 01:27 UTC, davidhicks requested changes

2024-12-05 01:27 UTC, davidhicks commented on locations/react_server_components.py
> +def parse_rsc(data_raw: Iterable[int]) -> Iterator[tuple[int, Any]]:
Thanks for writing this deserialization function! I've tried to track down the authoritative reference and seemingly it is the parseModelString() function at React's [/packages/react-server/src/ReactFlightReplyServer.js](https://github.com/facebook/react/blob/main/packages/react-server/src/ReactFlightReplyServer.js)

If this is correct, could a reference be provided to the React source code identified above, as it seems to document the meaning of all these abbreviations such as "G", "f", "g", "d", etc. I haven't found any authoritative React documentation in human-readable format that describes this serialization format.

2024-12-06 01:55 UTC, davidhicks commented on locations/react_server_components.py
> +def parse_rsc(data_raw: Iterable[int]) -> Iterator[tuple[int, Any]]:
Thank you, the documentation added is great! I'm not a React person but it's astonishing to me how poorly documented that serialization format appears to be.

2024-12-06 04:27 UTC, davidhicks approved these changes

2024-12-09 16:54 UTC, iandees commented
Nice, thanks for adding the parser!

2024-12-15 16:46 UTC, merged