Spider for South Carolina
alltheplaces/alltheplaces pull request #2976
Opened 2021-09-23 20:28 UTC by boomerwv1

Adding spider for South Carolina.

2021-09-23 20:32 UTC, iandees commented
These look like a bunch of different kinds of places. Everything from DMV to Library to event center. I'm a little hesitant to include these because it's a collection of different places not owned/run by the same company/organization.

When you did the scraping, did you see any information that you could use to build a category so that a data user could tell the different between all the different kinds of data in here?

2021-09-23 20:44 UTC, jleedev commented
The categories are as follows:

1. State Parks
2. Libraries
3. Department of Health and Human Services (DHHS)
4. Court Houses
5. Department of Mental Health (DMH)
6. Department of Motor Vehicles (DMV)
7. SC Works

Which could either be used as straight text, e.g. `type=*` or by mapping to an appropriate OSM tag.

2021-09-24 02:12 UTC, boomerwv1 commented
Yes, we can break it down into those 7 categories. We can do whatever way you think is best.

2021-09-24 02:52 UTC, iandees commented
Can you add an extra property called "category" for now and throw those in there?

2021-09-24 15:15 UTC, jleedev requested changes

2021-09-24 15:15 UTC, jleedev commented on locations/spiders/south_carolina.py
> +        zipre = response.xpath('//body//text()').extract()
The response body is JSON and should be accessed with `response.json()`.

2021-09-24 15:15 UTC, jleedev commented on locations/spiders/south_carolina.py
> +                            'postcode': '',
Should be `["Zipcode"]` of the record.

2021-09-24 15:15 UTC, jleedev commented on locations/spiders/south_carolina.py
> +    item_attributes = {'brand': "State of South Carolina", 'brand_wikidata': "Q53709977"}
I'd leave these off since they don't really make sense as OSM brand tags. The `@spider` attribute is sufficient to identify what these items are.

2021-09-27 14:54 UTC, boomerwv1 reviewed
Suggest changes have been made.

2021-09-27 14:59 UTC, merged