Adds Farmer Boy's Spider
alltheplaces/alltheplaces pull request #4058
Opened 2022-10-03 13:26 UTC by stephinson

Scrapes 100 [locations](https://www.farmerboys.com/locations/)

Closes https://github.com/alltheplaces/alltheplaces/issues/3530

Here's the sample output:

```json
{"type": "Feature", "id": "8UiK4I64urhrJQSZF3xz5ySVQxE=", "properties": {"ref": "baldwin-park-merced-ave", "@spider": "farmerboys", "addr:street": "14430 Merced Ave.", "addr:city": "Baldwin Park", "addr:state": "CA", "addr:postcode": "91706", "addr:country": "US", "name": "Baldwin Park - Merced Ave.", "phone": "(626) 856-1000", "website": "https://www.farmerboys.com/locations/location-detail.php?loc=baldwin-park-merced-ave", "opening_hours": "Mon-Sun  6:00a-12:00a", "brand": "Farmer Boy's"}, "geometry": {"type": "Point", "coordinates": [-117.962104, 34.072683]}},
{"type": "Feature", "id": "JBXNafOxNrkP615zMzgBWMSxWsA=", "properties": {"ref": "beaumont-2nd-street-marketplace", "@spider": "farmerboys", "addr:street": "1538 2nd St. Marketplace", "addr:city": "Beaumont", "addr:state": "CA", "addr:postcode": "92223", "addr:country": "US", "name": "Beaumont - 2nd St. Marketplace", "phone": "(951) 845-4414", "website": "https://www.farmerboys.com/locations/location-detail.php?loc=beaumont-2nd-street-marketplace", "opening_hours": "Mon-Sat 6:00a-9:00p Sun 7:00a-9:00p", "brand": "Farmer Boy's"}, "geometry": {"type": "Point", "coordinates": [-116.956538, 33.923217]}},
{"type": "Feature", "id": "Ucq0OkK9h3xcmGxDsOuSN0W7AaU=", "properties": {"ref": "bloomington-south-riverside-ave", "@spider": "farmerboys", "addr:street": "3356 S. Riverside Ave.", "addr:city": "Bloomington", "addr:state": "CA", "addr:postcode": "92316", "addr:country": "US", "name": "Bloomington - S. Riverside Ave.", "phone": "(951) 248-1244", "website": "https://www.farmerboys.com/locations/location-detail.php?loc=bloomington-south-riverside-ave", "opening_hours": "Mon-Sat 6:00a-10:00p Sun 7:00a-10:00p", "brand": "Farmer Boy's"}, "geometry": {"type": "Point", "coordinates": [-117.367757, 34.03887]}},
{"type": "Feature", "id": "IgzQqkNxeVTc_zDP5bB4c8uPrA8=", "properties": {"ref": "bloomington-valley-blvd", "@spider": "farmerboys", "addr:street": "18694 Valley Blvd.", "addr:city": "Bloomington", "addr:state": "CA", "addr:postcode": "92316", "addr:country": "US", "name": "Bloomington - Valley Blvd.", "phone": "(909) 873-5800", "website": "https://www.farmerboys.com/locations/location-detail.php?loc=bloomington-valley-blvd", "opening_hours": "Mon-Sat 6:00a-10:00p Sun 7:00a-10:00p", "brand": "Farmer Boy's"}, "geometry": {"type": "Point", "coordinates": [-117.396634, 34.070685]}},
{"type": "Feature", "id": "bQFPJxWsLBkfKF40hot1fASpjJI=", "properties": {"ref": "brea-lambert-rd", "@spider": "farmerboys", "addr:street": "500 W. Lambert Rd.", "addr:city": "Brea", "addr:state": "CA", "addr:postcode": "92821", "addr:country": "US", "name": "Brea - W. Lambert Rd.", "phone": "(714) 990-2424", "website": "https://www.farmerboys.com/locations/location-detail.php?loc=brea-lambert-rd", "opening_hours": "Mon-Thur 6:00a-9:00p Fri-Sat 6:00a-10:00p Sun 7:00a-9:00p", "brand": "Farmer Boy's"}, "geometry": {"type": "Point", "coordinates": [-117.902041, 33.924327]}}

```

2022-10-03 14:59 UTC, Cj-Malone requested changes
This looks good, a few comments though.

2022-10-03 14:59 UTC, Cj-Malone commented on locations/spiders/farmerboys.py
> +    item_attributes = {"brand": "Farmer Boy's"}
```patch
-item_attributes = {"brand": "Farmer Boy's"}
+item_attributes = {"brand": "Farmer Boys", "brand_wikidata": "Q5435711"}
```

2022-10-03 15:03 UTC, Cj-Malone commented
It also looks like the image is available, as "https://www.farmerboys.com/images/locations/" + location_pic, it's not a requirement, but a nice to have.

2022-10-05 09:13 UTC, stephinson commented on locations/spiders/farmerboys.py
> +                    Selector(text=location["location_hours"]).xpath("//text()").getall()
That would've worked if all opening hours followed a pattern, but that's not the case

`Mon-Sun Dining Room  6:00a-10:00p Drive Thru 6:00a-11:00p`

2022-10-05 10:14 UTC, Cj-Malone approved these changes
IMO less than 100% coverage, but parsable opening hours is better than 100% of opening hours that aren't parsable. But I'm happy to clean this up in another PR.

This looks good to go, thank you.

2022-10-06 02:18 UTC, merged