fixing spider for Loblaws
alltheplaces/alltheplaces pull request #4113
Opened 2022-10-17 15:57 UTC by boomerwv1

2022-10-17 16:44 UTC, Cj-Malone requested changes
Looks good, but a little to do.

Do we need to check `storeBannerId` to see what type of store it is? (Are they all brand=Loblaws?)
| count | storeBannerId           |
|-------|-------------------------|
| 5     | "independentcitymarket" |
| 11    | "dominion"              |
| 14    | "rapid"                 |
| 30    | "extrafoods"            |
| 43    | "zehrs"                 |
| 44    | "fortinos"              |
| 52    | "rass"                  |
| 60    | "loblaw"                |
| 61    | "wholesaleclub"         |
| 76    | "valumart"              |
| 124   | "superstore"            |
| 125   | "maxi"                  |
| 162   | "provigo"               |
| 216   | "independent"           |
| 425   | "nofrills"              |

Can we add the website? It seems to be `https://www.loblaws.ca/store-locator/details/{ref}`

The black test is failing because it wants the file to be formatted in a specific way, it's not the end of the world, but if you want to fix it. You may need to install black with something like `pip install black` and then run it on the file `black locations/spiders/loblaws.py`

2022-10-17 16:44 UTC, Cj-Malone commented on locations/spiders/loblaws.py
>      item_attributes = {"brand": "Loblaws"}
```suggestion
    item_attributes = {"brand": "Loblaws", "brand_wikidata": "Q3257626"}
```

2022-10-17 16:44 UTC, Cj-Malone commented on locations/spiders/loblaws.py
> +                    "lon": i["geoPoint"]['latitude'],
```suggestion
                    "lon": i["geoPoint"]['longitude'],
```

2022-10-17 16:45 UTC, Cj-Malone commented on locations/spiders/loblaws.py
> +                    "addr_full": i["address"]["line1"],
```suggestion
                    "street_address": ", ".join(
                        filter(
                            None, [i["address"].get("line2"), i["address"].get("line1")]
                        )
                    ),
```

2022-10-17 17:53 UTC, boomerwv1 commented
Good question. It looks like Loblaws if the parent company of all of these names. They are described as

`operating under 22 regional and market-segment banners`

Loblaws is one of these banners with approx 60 locations. I'm open to suggestions on if we want to include all of the banners in this spider or just the specific Loblaws branded ones.

2022-10-17 19:19 UTC, Cj-Malone commented
I think yes, we want to harvest this data in this spider. If we had a separate spider for them we wouldn't want to duplicate the data, but since we don't lets collect them in this spider.

Before the yield I'd do something if storeBannerId == nofrills: brand = No Frills brand_wikidata = Q3342407 elif ...

You can find some of the wikidatas [here](https://www.wikidata.org/wiki/Q909856#P355), you may have to search for some not listed.

2022-10-17 19:31 UTC, boomerwv1 commented
Works for me. I'll update that.

2022-10-18 14:28 UTC, Cj-Malone commented on locations/spiders/loblaws.py
> +                    "lon": i["geoPoint"]['latitude'],
This seems to have been reverted, https://data.alltheplaces.xyz/map.html?show=https://data.alltheplaces.xyz/ci/3274104279/loblaws/output.geojson

2022-10-18 15:42 UTC, Cj-Malone approved these changes
LGTM, thank you 😊

2022-10-18 15:49 UTC, merged