Fix yettel_bg spider
alltheplaces/alltheplaces pull request #6357
Opened 2023-11-20 10:13 UTC by Dimitar5555

Resolves #6323

2023-11-20 15:57 UTC, davidhicks requested changes

2023-11-20 15:57 UTC, davidhicks commented on Pipfile
> +openpyxl = "*"
You'll need to run `pip lock` to update `Pipfile.lock` and then add to this PR.

2023-11-21 10:03 UTC, Cj-Malone commented on locations/spiders/yettel_bg.py
> +    start_urls = ["https://www.yettel.bg/dA/1d9e589cca"]
The spreadsheet has already changed to ``.

I recommend starting with the store finder and extracting the url from there:
```suggestion
    start_urls = ["https://www.yettel.bg/faq/digital-customer-service/store-locator"]
```

2024-03-03 04:08 UTC, CloCkWeRX commented
Conflicts at the moment.

If you need a quick instance, maybe start a code space for this branch. Will be clunky but let you check everything is happy

2024-03-05 09:34 UTC, Dimitar5555 commented
It seems to work as expected now.

2024-03-05 17:03 UTC, iandees commented
It looks like you might have been running something other than Python 3.11 when you updated the Pipfile. Can you double-check that?

2024-03-05 18:08 UTC, Dimitar5555 commented
> It looks like you might have been running something other than Python 3.11 when you updated the Pipfile. Can you double-check that?

It was 3.10. Should be fixed now.

2024-03-15 20:36 UTC, merged