Add fielmann spider (758 locations)
alltheplaces/alltheplaces pull request #7097
Opened 2024-02-09 23:28 UTC by gorgobacka

Adding a spider for several country specific Fielmann websites. Some need a different parsing and are excluded for now.

It's my first spider for this project. Please let me know, if I can improve something.

```
{'atp/brand/Fielmann': 758,
 'atp/brand_wikidata/Q457822': 758,
 'atp/category/shop/optician': 758,
 'atp/field/country/from_website_url': 758,
 'atp/field/email/missing': 758,
 'atp/field/image/missing': 758,
 'atp/field/opening_hours/missing': 1,
 'atp/field/operator/missing': 758,
 'atp/field/operator_wikidata/missing': 758,
 'atp/field/phone/missing': 2,
 'atp/field/twitter/missing': 758,
 'atp/nsi/perfect_match': 758,
 'downloader/request_bytes': 653819,
 'downloader/request_count': 768,
 'downloader/request_method_count/GET': 768,
 'downloader/response_bytes': 38282263,
 'downloader/response_count': 768,
 'downloader/response_status_count/200': 768,
 'elapsed_time_seconds': 781.528712,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 2, 9, 23, 45, 31, 103914, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 247111607,
 'httpcompression/response_count': 768,
 'item_scraped_count': 758,
 'log_count/DEBUG': 1537,
 'log_count/INFO': 23,
 'memusage/max': 311762944,
 'memusage/startup': 142843904,
 'request_depth_max': 1,
 'response_received_count': 768,
 'robotstxt/request_count': 5,
 'robotstxt/response_count': 5,
 'robotstxt/response_status_count/200': 5,
 'scheduler/dequeued': 763,
 'scheduler/dequeued/memory': 763,
 'scheduler/enqueued': 763,
 'scheduler/enqueued/memory': 763,
 'start_time': datetime.datetime(2024, 2, 9, 23, 32, 29, 575202, tzinfo=datetime.timezone.utc)}
```

2024-02-10 09:23 UTC, davidhicks requested changes
Thanks for the first contribution!

This spider is using structured data (application/ld+json) and ATP is able to parse this information automatically. In this case, the type of "Optician" which is missing from the list of extracted types in `structured_data_spider.py`. Once you add this, you can automatically extract store information:

```
pipenv run scrapy sd https://www.fielmann.de/niederlassungen/datteln/45711-castroper-strasse-24/
{'city': 'Datteln',
 'country': 'West',
 'email': None,
 'extras': {},
 'image': 'www.fielmann.de/img/fielmann-logo_black.svg',
 'lat': 51.6505861,
 'lon': 7.3383697,
 'name': 'Fielmann - Ihr Optiker in Datteln, Castroper Straße 24',
 'opening_hours': 'Mo-Fr 09:00-18:30; Sa 09:00-14:00',
 'phone': None,
 'postcode': '45711',
 'ref': 'https://www.fielmann.de/niederlassungen/datteln/45711-castroper-strasse-24/',
 'state': 'Westfalen Süd',
 'street_address': 'Castroper Straße 24',
 'website': 'https://www.fielmann.de/niederlassungen/datteln/45711-castroper-strasse-24/'}
```

For this brand, each sitemap (DE, AT, CH, PL, CZ) should be split into their own spiders which allows them to run in parallel, and a fault in one spider not impacting the other countries.

Take a look at `five_guys_be.py` and other Five Guys spiders for something you can probably just copy+paste and rename.

In the example automatic scraper output above, you'll see the `image` field is not specific to the store and should be removed. To do this, just add method:

```
def post_process_item(self, item, response, ld_data):
    item.pop("image", None)
    # and any other cleanups you may want to do, or extra fields of data to extract manually
    yield item
```

2024-02-10 19:23 UTC, gorgobacka commented
Thanks a lot for your detailed review and it's nice to hear that it can be done much easier.
I just started my vacation today. But when I'm back in a few days, I will implement your suggestions.

2024-02-14 19:26 UTC, gorgobacka commented
@davidhicks I implemented your requested changes. Can you please check my PR again?

2024-02-14 20:35 UTC, CloCkWeRX approved these changes

2024-02-14 20:55 UTC, iandees approved these changes

2024-02-14 20:56 UTC, merged