[Pipelines] Add pipeline to clean addresses
alltheplaces/alltheplaces pull request #7568
Opened 2024-02-25 14:12 UTC by Cj-Malone

Rel: https://github.com/alltheplaces/alltheplaces/pull/7355#discussion_r1501312149

TODO:
- [ ] Check this actually improves the addresses (Will check against Weekly that is currently running)
- [ ] Migrate spiders from `vapestore_gb.clean_address`

2024-02-25 14:20 UTC, davidhicks commented
I haven't been using `vapestore_gb.clean_address` but have bee using a lot of similar code throughout spiders that can also be cleaned up.

I wonder whether we should allow `Item.street_address` and `Item.addr_full` to both be ordered lists, as well as strings (current situation). A spider could populate `Item.street_address = [ address1, address2]` which this new pipeline can then join together into a single string? Maybe this just makes things way more messy because the order of this new pipeline could get quite tricky.

2024-02-25 14:24 UTC, davidhicks requested changes

2024-02-25 14:24 UTC, davidhicks commented on locations/pipelines/address_clean_up.py
> +            if isinstance(street_address, str):
This is what I read first, not realising that `clean_address` has been designed to accept lists of strings. Should an `isinstance(street_address, list)` be added here too as an OR condition?

2024-02-25 14:24 UTC, davidhicks commented on locations/pipelines/address_clean_up.py
> +            if isinstance(addr_full, str):
Should an isinstance(street_address, list) be added here too as an OR condition?

2024-02-25 15:18 UTC, Cj-Malone commented
I wish we had done things like `phone` and `email` as lists, then `;` joined on export. It would have made things nicer. However right now, I think it's too much work to ensure everything works. Maybe in the future.

2024-03-01 17:52 UTC, Cj-Malone commented
I think it improves the output, 79,677 changes to `addr_full` and 148,346 `street_address`.
The full list is [here](https://gist.github.com/Cj-Malone/3e98587c302ce4241fb230e8d9d511ac), but it's as you'd expect, eg:

```patch
-IOMEGA (M) SDN BHD , PLOT 44, BAYAN LEPAS INDUSTRIAL PARK 4,
+IOMEGA (M) SDN BHD, PLOT 44, BAYAN LEPAS INDUSTRIAL PARK 4
```

2024-03-01 18:57 UTC, Cj-Malone commented
I specifically made `clean_address` compatible, taking the lists so we wouldn't have to change existing spider code. But then instead of doing the automatic refactor, I spend my Friday evening manually changing every spider, dropping it when I could, moving directly to `merge_address_lines` when we have an array. :/

2024-03-01 22:49 UTC, CloCkWeRX commented on locations/spiders/auchan_hu.py
> +        item["addr_full"] = item["addr_full"]
Is this redundant now?

2024-03-02 09:57 UTC, Cj-Malone commented on locations/spiders/auchan_hu.py
> +        item["addr_full"] = item["addr_full"]
Yep, thanks.

2024-03-15 19:06 UTC, Cj-Malone commented
The longer this goes the more annoying this will be to merge.

I have no objection to closing it in favour of:

1. Status quo, leaving the function inside the spider, it's not ideal, but it's not hurting us.
2. "Dumb refactor", just move the function to shared code (`utils.py`?). The pipeline could come in a separate PR. 
3. 2 but leave the original function in but "deprecated", this will be a real small diff.

2024-03-16 00:31 UTC, iandees commented
FYI, marking a PR as ready for review (from a draft) doesn't trigger an email, so I don't know when that happens. Feel free to ping or request a review.

2024-03-16 00:35 UTC, merged