Backport class name generation improvements from autospidergen branch
alltheplaces/alltheplaces pull request #8984
Opened 2024-07-28 02:41 UTC by CloCkWeRX

Cherry pick 5e5a936785581a7dc8447db9bfdd817522483483 for class name generation

Another small chunk of https://github.com/alltheplaces/alltheplaces/pull/6526

2024-07-28 09:45 UTC, davidhicks approved these changes

2024-07-28 13:48 UTC, CloCkWeRX commented on locations/name_suggestion_index.py
> +        # Last attempt to find a fuzzy match for registered domain (exlcuding subdomains)
```suggestion
        # Last attempt to find a fuzzy match for registered domain (excluding subdomains)
```

2024-07-31 03:05 UTC, davidhicks requested changes

2024-07-31 03:05 UTC, davidhicks commented on tests/test_name_suggestion_index.py
> +        ("mai_dang_lao_mcdonalds_hk_mo", "MaiDangLaoMcDonaldsHKMOSpider"),
`MaiDangLaoMcDonaldsHKMOSpider` should now be `MaiDangLaoMcdonaldsHKMOSpider`... I think... after the recent changes of #8829 to automatically fix/set spider class names based on the spider `name` field.

2024-08-31 04:13 UTC, CloCkWeRX commented on tests/test_name_suggestion_index.py
> +        ("mcdonalds_fr", "McDonaldsFRSpider"),
```suggestion
        ("mcdonalds_fr", "McdonaldsFRSpider"),
```

2024-08-31 04:13 UTC, CloCkWeRX commented on tests/test_name_suggestion_index.py
> +        ("mcdonalds", "McDonaldsSpider"),
```suggestion
        ("mcdonalds", "McdonaldsSpider"),
```

2024-08-31 04:14 UTC, CloCkWeRX commented on tests/test_name_suggestion_index.py
> +        ("mai_dang_lao_mcdonalds_hk_mo", "MaiDangLaoMcDonaldsHKMOSpider"),
```suggestion
        ("mai_dang_lao_mcdonalds_hk_mo", "MaiDangLaoMcdonaldsHKMOSpider"),
```

2024-08-31 04:16 UTC, CloCkWeRX commented on tests/test_name_suggestion_index.py
> +        ("mcdonalds", "McdonaldsSpider"),
```suggestion
        # NOTE: Spider naming convention tools ignore english naming conventions. While there are some inconsistencies in what humans would choose to do, that is acceptable.
        ("mcdonalds", "McdonaldsSpider"),
```

2024-08-31 05:02 UTC, CloCkWeRX commented
Thinking about this one, do we just want to fix the spider naming consistency check to be smarter for:

- Acronyms (BNPFooSpider)
- Common name capitalisation patterns (McDonalds)
- Country codes at end of spider (Brand It)

Or do we want to have our code smush the human naming from the NSI into a class name?

From the ruby world; the former would be done by:

- Add and maintain a list of text inflection capitalisatons - https://stackoverflow.com/questions/803262/how-do-i-tell-rails-how-to-correctly-capitalize-an-acronym

https://github.com/ixmatus/inflector/blob/master/tests/tests.py looks like a python port

2024-09-28 12:28 UTC, closed without merging