Add bobablastic
alltheplaces/alltheplaces pull request #9906
Opened 2024-08-27 13:06 UTC by CloCkWeRX

Fix https://github.com/alltheplaces/alltheplaces/issues/9829

2024-08-27 13:21 UTC, CloCkWeRX commented
This might actually be 50 locations. Storefinder is pretty broken

2024-08-27 16:13 UTC, davidhicks requested changes
Suggestions for bringing this spider up to the proposed standard set in #9916:

* Specify `days=DAYS_EN`.
* Remove `time_format`.
* Add `"extras": Categories.FAST_FOOD.value` to `item_attributes`.

Have you tried also adding the following to check if more than 50 locations exist:
```
iseadgg_countries_list = ["US"]
search_radius = 100
max_results = 50
```

If you still see only 50 results with this approach, then seemingly there are indeed 50 stores.

2024-08-27 22:01 UTC, CloCkWeRX commented
Oops, lost a store in mexico

2024-08-28 08:15 UTC, CloCkWeRX commented on locations/spiders/bobablastic_us.py
> +    time_format = "%I:%M %p"
```suggestion
```

2024-08-28 15:07 UTC, davidhicks approved these changes

2024-08-28 15:30 UTC, merged