Add eriks_delicafe
alltheplaces/alltheplaces pull request #9908
Opened 2024-08-27 13:25 UTC by CloCkWeRX

Fix https://github.com/alltheplaces/alltheplaces/issues/9825

2024-08-27 16:09 UTC, davidhicks requested changes
Suggestions for bringing this spider up to the proposed standard set in #9916:

* Rename spider to have "_us" suffix.
* Specify `days=DAYS_EN`.
* Remove `time_format`.
* Add `"extras": Categories.FAST_FOOD.value` to `item_attributes`.

2024-08-28 05:42 UTC, davidhicks requested changes
Now that #9916 is merged, the final change needed here is to remove the `time_format` attribute as this is deprecated/no longer required. Then this is good to go.

2024-08-28 08:13 UTC, CloCkWeRX commented on locations/spiders/eriks_deli_cafe_us.py
> +    time_format = "%I:%M %p"
```suggestion
```

2024-08-28 08:38 UTC, davidhicks approved these changes

2024-08-28 14:06 UTC, merged